### ISSUE TITLE
Step 1: Create shapefile when village-level shapefile is unavailable 

### ISSUE THREAD

**Issue by davidn10** [SSA-Statistical-Team-Projects/SAEplus#1]
1. Function accepts admin-0 shapefile and population raster file (supplied by user) 
2. Function uses st_make_grid to create grids (dimensions specified by user) 
3. Function calculates population sums by tile (using exact_extractr)
4. Function creates new shapefile with tile IDs by masking out tiles with population with population zero

**Comment by takaakimasaki** [comment]
@ifeanyi588 I've uploaded sample scripts to generate raster, turn it into polygons, and then compute zonal statistics. These scripts can be found in https://github.com/SSA-Statistical-Team-Projects/SAEplus/tree/sample_scripts/sample.

**Comment by davidn10** [comment]
Great, Can you also compute zonal stats for open street map? I will send you my scripts

**Comment by ifeanyi588** [comment]
The function also computes total population for each polygon. Which is the used to estimate population size for the entire region. Is this what you mean? 

Ify
