### ISSUE TITLE
Write saeplus_selectmodel(dt, outcome_var, normalize = FALSE)

### ISSUE THREAD

**Issue by ifeanyi588** [SSA-Statistical-Team-Projects/SAEplus#14]
Write an saeplus_selectmodel(dt, outcome_var, normalize = FALSE) function that takes the arguments stipulated. It prepares the data for lasso regression, if user inputs normalize = TRUE, will actually normalize the X variables and before running the lasso regression. The function will return a list object with 2 items: the summary of the lasso regression as well as the coefs as in David's sample code.

**Comment by davidn10** [comment]
Thanks, Ify. I suspect that the rlasso function in the hdm package already normalizes the X variables before doing the lasso regression, so I’m not sure the normalize option will have any effect. My recollection is that normalizing the Xes is standard practice for lasso.  Checking the hdm documentation could verify that. 
Later, we could add a package option that would default to hdm but would take glmnet as an option, but that’s not essential right now.

Best,
David
