### ISSUE TITLE
3 major sources of population data

### ISSUE THREAD

**Issue by takaakimasaki** [SSA-Statistical-Team-Projects/SAEplus#2]
There are three major sources of population data: 

1. WorldPop (https://www.worldpop.org/)
-Constrained
-Unconstrained
-Bespoke methods - https://wopr.worldpop.org/?SSD/
2. GHS-POP (https://ghsl.jrc.ec.europa.eu/download.php?ds=pop)
3. HRSL (Facebook and CIESIN) (https://www.ciesin.columbia.edu/data/hrsl/)

**Comment by takaakimasaki** [comment]
@ifeanyi588 @davidn10 It will be important to check how population numbers may differ across these different sources.

**Comment by ifeanyi588** [comment]
Dear Taka, 

Thank you for sending this. However, the R package will not be able to render if I accepted your branch as is. What we need to do is a create a folder for raw data by using the following command in your R console: usethis::use_data_raw(). I could also just do this myself if you dont have time. This will create a folder called data-raw but the R package building functions will recognize it when we officially deploy the package in the future. 

Best regards,
Ify

**Comment by ifeanyi588** [comment]
Dear @takaakimasaki,

Thanks for the raw data you sent. I have uploaded it into the raw-data folder as per the email above. I will go ahead and address David's issues now and get back to you if I have any questions. Thanks again for your help! 

Best regards,
Ify

**Comment by takaakimasaki** [comment]
Dear @ifeanyi588,

Ah perfect! I actually did not know how to do that and it's useful to know how that works.

**Comment by ifeanyi588** [comment]
> @ifeanyi588 @davidn10 It will be important to check how population numbers may differ across these different sources.

@takaakimasaki I am going to try to add capability to the function that allows the user compare population estimates from the three sources
