### ISSUE TITLE
Fix “wpopbuilding_vcheck" and “wpopbuilding_pull”  functions 

### ISSUE THREAD

**Issue by rahim03** [SSA-Statistical-Team-Projects/SAEplus#24]
Dear @ifeanyi588 ,

When I tried to run these functions outside the package, I get an error :  
**"Error in function (type, msg, asError = TRUE)  : <not set>"**
Please could you check and fix the problem.

Best,
Rahimatou

**Comment by ifeanyi588** [comment]
Dear @dasalm20, 

We need to fix the wpopbuilding_vcheck() and wpopbuilding_pull() functions to be able to pull data from world pop. Please check specifically if we need to update the web links which the functions read from. 

Best regards,
Ify
