### ISSUE TITLE
Inspect gengrid

### ISSUE THREAD

**Issue by ifeanyi588** [SSA-Statistical-Team-Projects/SAEplus#7]
Dear @rahim03,

I have written the gengrid() function and pushed to the branch construct_shapefile. This is supposed to address the first issue which David wanted done (find this under the Issues tab). I would like you to do the following: 

- First make sure SAEplus on your computer is up to date by first clicking pull in your github window. 
- Then run renv::restore() just to ensure R package dependencies are up to date as well. 
- Then I would like you to run the gengrid() function. I want to see if it actually runs correctly. 
- Once you have done the above, write a response to this issue to confirm whether or not it works. If we are satisfied with it, you will be the one to accept my branch into master. 

Please let me know if you have any questions. 

Best regards,
Ify

**Comment by rahim03** [comment]
Dear @ifeanyi588 ,
I followed the steps you described in the previous comment. And the function works well.

**Comment by ifeanyi588** [comment]
Dear @rahim03, 

Perfect! Now I have a task for you. This R package is about building the set of tools in R that we can use to combine geospatial data especially from remote sensing sources (e.g googleearth engine) towards inputs for running small area estimation in R (sae) with EMDI package. However, we have a more important task of using these tools estimate the poverty rates for Chad and Mali using the data @davidn10 sent us. So for your next task, please do the following: 

- Create a new github project titled "S2S-REMDI" (i.e survey to survey imputation using the R's EMDI package). This WILL NOT be an R package. Just a Git project so that we can version control our work to make our lives easier. 
- Next, go to RStudio and create a new version control project just like I showed you and use this link to the github project you created to pull this empty project onto your computer. 
- Next, create a folder with an SSA countryname that will contain the same set of folders as in a harmonization folder on the SSAPOV server. This will be the format for each folder which we will use for our imputations. We need to do this for Mali and Chad. In other words, create a folder called MLI_2021 which will contain folders "02.Output", "Data", "DDI", "Doc", "Programs". Do the same for TCD_2021. 
- If you run devtools::install_github("SSA-Statistical-Team-Projects/SAEplus"), it should load all the functions written in our package and you should be able to use it like any other R package. If this doesnt work for whatever reason, simply go to the R folder in this project and copy all the functions into one R script and load them in the Programs folders in MLI_2021 and TCD_2021. 
- I will send you a shapefile to place in the Data folders, run the function gengrid() (which I have updated), on the shapefiles to generate the polygonized population counts and save the results with an appropriate name in the Data folders. 

There will be more to come as we develop the R package alongside this imputation exercise for Mali and Chad. I am currently working on some functions to pull the geospatial data from R which you (or me if you are not yet setup) can run for Mali and Chad and combine with the polygonized data which gengrid() created. 

Best regards,
Ify
